### ISSUE TITLE
Can online calibration of the extrinsic parameters with an IMU works?

### ISSUE THREAD

**Issue by Qsminefor** [KAIST-VCLAB/sphere-stereo#4]
Hi! Thank you for your great work. I would like to ask a question about the extrinsic parameters in this work. In the 'calibration.json', the extrinsic parameters are fixed. If the cameras move, the parameter should be calibrated again. Is it right? Could I solve this question by adding an IMU to correct the extrinsic parameters of the cameras. I would appreciate it if you have any suggestions about that.
Thank you again!

**Comment by ameuleman** [comment]
Hi, thank you for your interest! 
If the cameras move with respect to each other (i.e. they don't move together) then they need to be recalibrated. Adding an IMU to each camera may help knowing their relative locations for short displacements, but IMUs are likely to be subject to drift for longer sequences.
Please let me know if you need further explanations or details.

**Comment by Qsminefor** [comment]
Thank you for your quick response and your valuable suggestions! 
I would like to know if the 4 cameras move together, should the extrinsic parameters (T_imu_cam) be calibrated? In my opinion, the suite moves, and the extrinsic parameters changed, is it right?

**Comment by ameuleman** [comment]
The cameras' extrinsic parameters only need to be accurate w.r.t. each other for the sphere sweeping algorithm (the first camera is set to identity by default). If the rig maintains the cameras together there should be no issue moving it.

**Comment by Qsminefor** [comment]
Got it. Thank you for your nice and useful response.
