### ISSUE TITLE
stitching 

### ISSUE THREAD

**Issue by ynma-hanvo** [KAIST-VCLAB/sphere-stereo#5]
thanks for the great work.
I have checked the points generated in one reference camera,  it  has some long tail part.
does the stitching remove some depth which is bad in one reference camera,  if so. how can i generate points from the stitched depth map. 
thanks again ,  your work is really appreciated.

**Comment by ameuleman** [comment]
Hello,
In https://github.com/KAIST-VCLAB/sphere-stereo/blob/master/python/stitcher.cu, `unitPointPanorama` gives the direction corresponding to a pixel. Multiplying this vector by the corresponding distance will provide the 3D point position.

**Comment by ynma-hanvo** [comment]
ye,  I got it and thanks very much for your quick reply.
